export enum DeviceType {
  Light = 'devices.types.light',
  Socket = 'devices.types.socket',
  Switch = 'devices.types.switch',
  Thermostat = 'devices.types.thermostat',
  ThermostatAC = 'devices.types.thermostat.ac',
  Media = 'devices.types.media_device',
  Tv = 'devices.types.media_device.tv',
  TvBox = 'devices.types.media_device.tv_box',
  Receiver = 'devices.types.media_device.receiver',
  Cooking = 'devices.types.cooking',
  Kettle = 'devices.types.cooking.kettle',
  CoffeeMaker = 'devices.types.cooking.coffee_maker',
  Multicooker = 'devices.types.cooking.multicooker',
  Openable = 'devices.types.openable',
  Curtain = 'devices.types.openable.curtain',
  Humidifier = 'devices.types.humidifier',
  Purifier = 'devices.types.purifier',
  VacuumCleaner = 'devices.types.vacuum_cleaner',
  WashingMachine = 'devices.types.washing_machine',
  Dishwasher = 'devices.types.dishwasher',
  Iron = 'devices.types.iron',
  Sensor = 'devices.types.sensor',
  Other = 'devices.types.other',
}
